# Generated by Django 4.2.3 on 2023-11-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_course_category_alter_course_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
