# Generated by Django 4.2.3 on 2023-11-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_userprofile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_credit_update',
            field=models.DateTimeField(null=True),
        ),
    ]
