# Generated by Django 4.2.3 on 2023-11-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userprofile_last_credit_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_credit_update',
        ),
    ]
